### ISSUE TITLE
Errors: "stderr maxBuffer exceeded."

### ISSUE THREAD

**Issue by reggi** [ipselon/structor#1]
`["stderr maxBuffer exceeded."]`
`[[["Cannot find module 'lodash/lang/isFunction'"," @ multi main"]]]`
 
![screen shot 2015-10-18 at 8 42 47 pm](https://cloud.githubusercontent.com/assets/296798/10567687/e2e1ccde-75d8-11e5-8297-7b2e256f79a6.png)

**Comment by ipselon** [comment]
Please, describe your environment and steps you were doing.

**Comment by reggi** [comment]
I tried to clone the default project and this happened.

```
$ node -v
v4.1.0
$ sw_vers -productVersion
10.10.5
```

**Comment by yaycmyk** [comment]
The lodash/lang/isFunction issue is usually due to not having lodash in your project, but it's a dependency in a consumed npm module.

**Comment by ipselon** [comment]
I'm not sure that structor works on node version 4.x
