### ISSUE TITLE
babel 5 is no longer maintained

### ISSUE THREAD

**Issue by vedmalex** [ipselon/structor#14]
Hi, on Ubuntu 14.04.3 node 5.1 already installed babel.js 6.3 
the message while installation 
```
npm WARN deprecated babel-core@5.8.25: Babel 5 is no longer being maintained. Upgrade to Babel 6.
```

**Comment by ipselon** [comment]
Hi, that is true, Structor does not work with babel 6, but I can't upgrade babel because of the issue in babel-plugin-react-transform: https://github.com/gaearon/babel-plugin-react-transform/pull/50

**Comment by vedmalex** [comment]
Ok, Thank you for fast response. I understand it now.

**Comment by ipselon** [comment]
I'm closing this issue, will migrate to babel 6 as soon as babel-plugin-react-transform will be updated.
