### ISSUE TITLE
Can't open `http://localhost:2222/structor`

### ISSUE THREAD

**Issue by Xuhao** [ipselon/structor#2]
I create a new folder `structor`, I go to this folder and run `structor .`, it say:

```
Structor started successfully.
Please go to http://localhost:2222/structor
```

Then I go to  http://localhost:2222/structor in browser, but I got:
```
SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
Protocol mismatch.
```

My env:
Mac OS X 10.10.5
node v0.12.3
npm 2.14.0

**Comment by ipselon** [comment]
Not sure that this is an issue with Structor.

**Comment by Xuhao** [comment]
@ipselon Yes, it's because port collision for 22 => 2222 from my VM. Thanks for remind.

**Comment by ipselon** [comment]
to set another port: ```structor -p <port>```

**Comment by Xuhao** [comment]
@ipselon :+1:  Thanks!
