### ISSUE TITLE
Extend the idea of how to visually compose Web components and fill in the gap with code that glues things together.

### ISSUE THREAD

**Issue by ipselon** [ipselon/structor#20]
The idea of how to visually compose Web components and fill in the gap with code that glues things together is partially resolved in Structor so far. 

But we are not going to leave things as they are, because we want to build a sophisticated system, which will guide developers to use the best practices in Web app development. Of cause, there are different practices, that's why we want to understand what ways will be preferred to build a Web app using different technics.

In short, Structor has the source code generators, which are the glue for components and other parts of Web app (framework parts). 

Could you tell what kinds of generators will be useful? 

For example:
a) Infrastructure generators:
* Generate REST service with Swagger docs by entered in Swagger configuration format.
* Generate GraphQL server by entered data structure in GraphQL schema format

b) Component generators:
* Generate Redux wrapped components connected to existing REST API
* Generate Relay wrapper components connected to existing GraphQL server

Any other ideas?

**Comment by brysgo** [comment]
This would be super cool and I would love to contribute!
