### ISSUE TITLE
Structor Market fails too easily

### ISSUE THREAD

**Issue by explorigin** [ipselon/structor#21]
Got to structor market or start a new project and you get this error:

> Got error code 404 processing request to https://api.github.com/repos/tirumudi/bootstrap-prepack

Seems like structor should fail a little more gracefully if a 3rd party resource becomes inaccessible.

**Comment by ipselon** [comment]
Yes, thanks, will fix it fast.

**Comment by ipselon** [comment]
Now everything is working good.

**Comment by explorigin** [comment]
Very nice.
