### ISSUE TITLE
Please check the prepacks, most of them have problems

### ISSUE THREAD

**Issue by explorigin** [ipselon/structor#22]
I was not able to install with npm errors:
- neal-react-prepack
- bootstrap-prepack

There are 2 prepacks named *material-ui-prepack*

structor-starter-prepack works but the server component throws this error: 

```
timothy@sardis:~/projects/structor-gallery$ node ./server.js
module.js:340
    throw err;
    ^

Error: Cannot find module './server/api'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/timothy/projects/structor-gallery/server.js:7:17)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Function.Module.runMain (module.js:457:10)

```

**Comment by ipselon** [comment]
Thanks for structor-starter-prepack - will fix it.

What errors you got during cloning neal-react-prepack and bootstrap-prepack ?

As for naming of prepacks, I can't moderate the names of repos on GitHub. What I can do is to add some label about cloned repos, later I will add this.

**Comment by explorigin** [comment]
![installation_error](https://cloud.githubusercontent.com/assets/697818/11632162/709ced6a-9ccb-11e5-9e66-393d7d76de40.png)

**Comment by ipselon** [comment]
It seems you are using npm3? Unfortunately, I'm not familiar with npm3 and don't know why some packages are not compatible with npm3 - I made this conclusion from screenshot.

**Comment by explorigin** [comment]
I don't know what npm3 is.  I appears that I'm running 1.4.10.

```
timothy@sardis:~/projects/structor-gallery$ npm --version
1.4.10
timothy@sardis:~/projects/structor-gallery$ npm3
No command 'npm3' found, did you mean:
 Command 'npm' from package 'npm' (universe)
npm3: command not found
```

**Comment by ipselon** [comment]
well, try to upgrade npm up to 2.x
BTW, did you delete some lines from server.js file in structor-starter-prepack before start node?

**Comment by explorigin** [comment]
Oh I see. I'm on Ubuntu 14.04 LTS.  It's probably just and old version.  It's not so easy to upgrade without messing with other things.

**Comment by ipselon** [comment]
Yeah, I think so, but, I've never work with npm less than 2-nd version.

**Comment by ipselon** [comment]
structor-starter-prepack is fixed https://github.com/ipselon/structor-starter-prepack/commit/1a42a72670002c46de045e5fa7cf0bdf25d8ac8b

**Comment by ipselon** [comment]
Will close issue - my prepacks are working as expected.

**Comment by explorigin** [comment]
You might consider adding an npm version check since 14.04 LTS is a common installation among developers.

**Comment by ipselon** [comment]
If there is such an option in package.json I will set this. Thanks.
