### ISSUE TITLE
The react component generator doesn't support nested spans.

### ISSUE THREAD

**Issue by hashtree** [ipselon/structor#24]
* Description: The react component generator doesn't support nested spans. Everything under an element span will be disappear in the post-code-generating snippet.

* Example:

**The tag tree looks like below:**
```html
<span>
    <FontIcon/>
    <span>something</span>
</span>
```
**The meta info looks like below(before component code generating):**
```javascript
{
    "type": "span",
    "text": " ",
    "children": [
        {
            "type": "FontIcon",
            "props": {
                "className": "iconfont icon-inbox",
            }
        },
        {
        	"type": "span",
            "text": "{this.props.comment.parent}",
        }
    ]
}
```
**The code under render looks like below(post component code generating):**
```html
<div style={ {    "marginTop": "10px"} }>
    <span>{ this.props.comment.time }</span>
    <span style={ {    "float": "right"} }>  
        <!-- suppose two more nested elements FontIcon&span should be inside here, but they aren't. -->
    </span> 
</div>
```

**Comment by ipselon** [comment]
There is distinction between text element and regular, so span element is a text element - that is why any nested elements are not rendering. Instead of span you can use any other, for example div.

**Comment by hashtree** [comment]
Thank you for the reply. I see, then have updated my code with work-around div inline properties.
