### ISSUE TITLE
Use acorn instead of esprima as AST parser.

### ISSUE THREAD

**Issue by teaegg** [ipselon/structor#25]
As far as i know, acorn is faster than esprima. 
also acorn is actively maintained and is used by babel.

**Comment by ipselon** [comment]
According to this benchmark esprima is faster http://esprima.org/test/compare.html

**Comment by mapduty** [comment]
https://facebook.github.io/react/blog/2015/06/12/deprecating-jstransform-and-react-tools.html#esprima-fb

**Comment by ipselon** [comment]
Yes, there is a trade off. And I think I will migrate to acorn if we have to parse JSX. Thanks for tip. Now there is no time to make such a migration, I'm busy with generators which will be installed separately.

**Comment by ariya** [comment]
esprima-fb is Facebook fork. The fact that it's deprecated doesn't affect the official Esprima project.
And yes, Esprima is still actively developed, I invite you to take a look at https://github.com/jquery/esprima/commits/master :smiley:

**Comment by ipselon** [comment]
@ariya thanks, I really like esprima, esprecially how contributors manage the source code - testing, contribution flow, examples.
