### ISSUE TITLE
wrap component inserts "Empty div" span above element being wrapped

### ISSUE THREAD

**Issue by psimyn** [ipselon/structor#27]
small one, but a bit annoying.

- Select an element in Hierarchy View
- Select "wrap", and wrap in a div
- Component is wrapped, but with an extra span above it

```
<div>
    <span>Empty div</span>
    <button>Button</button>
</div>
```

**Comment by ipselon** [comment]
Got it. Will think how to avoid such an inconvenience.

**Comment by psimyn** [comment]
Think I have solved in https://github.com/psimyn/structor/tree/wrap

in `client/src/api/utils.js`, I changed:

```
  case 'wrap':
    if (buffer && buffer.length > 0) {
+        options.children = buffer;                 
-        options.children.push(buffer[0]);                        
    }
```

This possibly will have terrible results, I haven't gone through fully but it seems to work..
