### ISSUE TITLE
HTML encoded entities in Component Hierarchy Edit Mode

### ISSUE THREAD

**Issue by psimyn** [ipselon/structor#29]
Unsure how html-encoded should be handled displayed, but currently inconsistent in 3 places.

In Component Hierarchy they are shown as text, in edit mode they are shown as entities.

![langnbsp](https://cloud.githubusercontent.com/assets/1731922/12058106/7e24890a-af9c-11e5-9f6f-ac4e1e229a4e.png)

In the main preview area they are shown as text (this is probably the one that actually matters..).

**Comment by ipselon** [comment]
Did fix this behaviour in new version.
