### ISSUE TITLE
structor command is unable to find ./server/api.js

### ISSUE THREAD

**Issue by supreetpal** [ipselon/structor#3]
Following the steps given to install, in both the scenarios (using empty folder or after running npm install on the downloaded folder from market). The command `structor .` throws an error. Find screenshot below:

Macbook Pro Retina 13inch - mid 2015
OSX El Capitan
npm -v 2.14.6
node -v 4.1.2

![screen shot 2015-10-19 at 12 22 55 pm](https://cloud.githubusercontent.com/assets/745581/10571386/4fa96010-765c-11e5-8cc2-841434475cce.png)

**Comment by ipselon** [comment]
I didn't test it on node 4.

**Comment by gebrits** [comment]
Samve problem on node version `v0.12.7`

**Comment by ipselon** [comment]
Try to reinstall with ```-g``` key.
```npm uninstall structor -g```
```npm install structor -g```

**Comment by supreetpal** [comment]
works.
