### ISSUE TITLE
Errors on cloned prepack

### ISSUE THREAD

**Issue by adambro** [ipselon/structor#32]
When clone from webapp failed (see #31) I've tried to download prepack and start structor from there. unfortunatley there were errors:

```
Cannot GET /deskpage/
["Cannot read property 'error' of undefined"]
```

Any hints how to help debug the project?

**Comment by ipselon** [comment]
@adambro what project you have cloned from market?

**Comment by adambro** [comment]
Tried both bootstrap-prepack and material-ui-prepack. Same error.

**Comment by ipselon** [comment]
After you download from GitHub or from market you need to run `npm install` in target firectory. And only after that start structor.

**Comment by ipselon** [comment]
But, it that does not help you have to reinstall babel and its modules right in the structor's directory, but before set struict numbers of babel modules in package.json. But this is rather frustrating I think. I need some time to fix this...

**Comment by adambro** [comment]
Of course I did `npm install` first, otherwise web interface would not start AFAIR. Any advice which babel version to put in package.json file?

**Comment by ipselon** [comment]
Try to set strict numbers which are in package.json, just remove `^` sign, delete node_modules and reinstall.

**Comment by adambro** [comment]
OK, I've set exact versions and run `npm i`. The same error again.
```
  "devDependencies": {
    "babel-core": "6.3.26",
    "babel-loader": "6.2.0",
    "babel-plugin-add-module-exports": "0.1.2",
    "babel-plugin-transform-runtime": "6.3.13",
    "babel-polyfill": "6.3.14",
    "babel-preset-es2015": "6.3.13",
    "babel-preset-react": "6.3.13",
    "babel-preset-stage-0": "6.3.13"
}
```

Didn't you confuse my 2 reported issues? The #31 was about babel.

**Comment by ipselon** [comment]
Sorry, I thought this is the same issue because you gave a reference. This case I need to investigate. Could you tell did reinstalling babel modules help for issue #31?

**Comment by adambro** [comment]
Yes, I've closed #31 just now.

**Comment by ipselon** [comment]
Well, thanks. Could you tell what OS, version of npm and node you are using?

**Comment by ipselon** [comment]
Also, could you zip your folder with cloned project from market (without node_modules) and sent this package to support@helmetrex.com ?

**Comment by adambro** [comment]
Zip with cloned prepack sent via mail. I'm using Arch Linux. Problem happens on Chrome and Firefox.
```
[adam@ThinkTank ~]$ npm --version
3.5.2
[adam@ThinkTank ~]$ node --version
v5.3.0
```

**Comment by ipselon** [comment]
Package you sent works with Structor in environment: npm 3.3.12, node 5.2.0, mac os x.
Will update node up to 5.3.0 and will try again.

**Comment by radman-x** [comment]
Also getting same error as adambro. Running on mac osx, latest mature version of node (v4.2.2).

Also, get error when creating custom component, when selecting "React component with all children". Are you able to create a custom component (say, similar to your video tutorial https://www.youtube.com/watch?v=JLz8B0XJPyk) with the latest Structor version (v0.2.6)?

**Comment by ipselon** [comment]
@radman-x I tried to clone and generate simple component and didn't get error. There is only one place where such error can be thrown, this is when client part of Structor make http request to Express server. In that case client uses `isomorphic-fetch` lib.

**Comment by adambro** [comment]
Any hints how to debug it to provide more information or fix it myself?

**Comment by ipselon** [comment]
@adambro please find in source `/src/client/src/actions/serverActions.js` file. Then go to 162 line - there our problem is (it seems to me).
There is no debug configuration, but you can build structor by yourself. Here is the instruction how to build and run locally structor from the build.
* clone this repo
* run `npm install`
* run `npm run build-client`
* run `npm run build-server`
* run `node structor.js -d <path to some empty folder>`

**Comment by adambro** [comment]
File `./src/client/actions/serverActions.js` in bootstrap prepack has got only 60 lines.

I've tried to build from source as you've sugested. Error `["Cannot read property 'error' of undefined"]` does not happen, but http://localhost:2222/deskpage/ still returns 404.

**Comment by ipselon** [comment]
@adambro are you trying to open http://localhost:2222/deskpage in browser? structor's URL is http://localhost:2222/structor

**Comment by ipselon** [comment]
As for `./src/client/actions/serverActions.js` I meant the file in the source code of structor.

**Comment by adambro** [comment]
As far as I can see structor tries to open http://localhost:2222/deskpage/  in an iframe - that's the main workspace. In iframe and in separate window I'm getting 404. Also http://localhost:2222/desk/__build__/bundle.js does not give any HTTP response when I look at network tab in FF inspector.

**Comment by ipselon** [comment]
It seems that you have some issues with dev-middleware of webpack. Let's try to see is it works: in the source code of structor find file `<structor source>/src/server/src/MiddlewareCompilerManager.js`, go to 109 line and change `true` to `false` in `noInfo` and `quit` fields accordingly. Try to build and run strucotr again.

**Comment by bradennapier** [comment]
This doesnt work for me either. 

I started with redux prepack and i got an error saying `.structor` didn't exist.  then I tried material and got the `can't GET /deskpage` error

**Comment by ipselon** [comment]
@bradennapier try to download and unpack prepack manually. Read about the second way for running structor here: https://github.com/ipselon/structor#getting-started

**Comment by jamesdwilson** [comment]
:+1:  tried on several environments, ubuntu linux. same cannot get deskpage.

**Comment by ipselon** [comment]
@jamesdwilson did you try to download manually? here is how to do that https://github.com/ipselon/structor#getting-started (the second way)

**Comment by jamesdwilson** [comment]
Yes, tried that way, tried with several node versions. Tried standalone
method 1 and tried method 2 with
https://github.com/ipselon/neal-react-prepack

On Wed, Feb 3, 2016 at 1:19 AM, Alex Pustovalov <notifications@github.com>
wrote:

> @jamesdwilson <https://github.com/jamesdwilson> did you try to download
> manually? here is how to do that
> https://github.com/ipselon/structor#getting-started (the second way)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipselon/structor/issues/32#issuecomment-179059744>.
>



-- 
Thank you!

**Comment by ipselon** [comment]
neal-react-prepack is compatible only with 0.2.0 version of structor. If you've installed version 0.2.7 please try bootstrap-prepack or material-ui.

**Comment by jamesdwilson** [comment]
Please mark that in bold on top of it. Thank you for your help and
wonderful products.

On Wed, Feb 3, 2016 at 1:31 AM, Alex Pustovalov <notifications@github.com>
wrote:

> neal-react-prepack is compatible only with 0.2.0 version of structor. If
> you've installed version 0.2.7 please try bootstrap-prepack or material-ui.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipselon/structor/issues/32#issuecomment-179066063>.
>



-- 
Thank you!

**Comment by ipselon** [comment]
Please find a label in the top of Readme on each project for Structor's compatibility. Thanks for your kind words.

**Comment by jamesdwilson** [comment]
Please make a feature that compares the template version with the maker.

On Wed, Feb 3, 2016 at 1:34 AM, Alex Pustovalov <notifications@github.com>
wrote:

> Please find a label in the top of Readme on each project for Structor's
> compatibility. Thanks for your kind words.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipselon/structor/issues/32#issuecomment-179067043>.
>



-- 
Thank you!

**Comment by ipselon** [comment]
@jamesdwilson could you elaborate on that feature? I'm not sure that I understand what the template and maker you meant.

**Comment by ipselon** [comment]
Need to close issue in view of new version.
