### ISSUE TITLE
JQuery exception when creating custom component on Mac OSX

### ISSUE THREAD

**Issue by radman-x** [ipselon/structor#35]
We have been researching Structor and trying to use it but are having numerous problems. The concept is very good but the tool is still too immature and buggy to use for real work. Here are some of our results and problems.

We are running on Mac OSX, 10.8.5 (Mountain Lion).
Initially, we started with:
     Structor v0.2.2
     node: v4.2.2 (LTS)
We were able to install and use this version of Structor somewhat. There were several errors but we were able to compose components and completed part 1 of the tutorial (https://www.youtube.com/watch?v=AY65e6Ry_rY). We were able to create custom components and partially complete part 2 of the tutorial fairly well (had a few errors but generally it seemed to work).

Next, we upgraded to the following in an attempt to fix some of the errors above:
    node: v5.3.0 (Stable)
    Structor: v0.2.6
We first uninstalled the old Structor (v0.2.2) and then did:
    sudo npm install Structor -g
During the installation, we got numerous warnings:
gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/user_name/.node-gyp/5.3.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/structor/node_modules/bufferutil/.node-gyp"
And errors such as:
npm ERR! Darwin 12.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "structor" "-g"
npm ERR! node v5.3.0
npm ERR! npm  v3.3.12
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read
npm ERR! network read ECONNRESET
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
It seems like some type of permissions problem or network error but we could not find anything obvious.

We then tried using Structor and could get to the point of starting a clone of Bootstrap pre-pack but then it just hung with the following error in console:
POST http://localhost:2222/invoke net::ERR_EMPTY_RESPONSE(anonymous function) @ main.js:28(anonymous function) @ main.js:26(anonymous function) @ main.js:26c.default.value @ main.js:66l.default.value @ main.js:66r @ main.js:9i @ main.js:9s @ main.js:9c @ main.js:9f @ main.js:9n @ main.js:9m.processEventQueue @ main.js:9r @ main.js:9a.handleTopLevel @ main.js:9i @ main.js:25a @ main.js:25o.perform @ main.js:23d.batchedUpdates @ main.js:24a @ main.js:23g.dispatchEvent @ main.js:25
2016-01-05 10:15:02.570 main.js:8 Uncaught (in promise) Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.(…)
Again, this seems like some type of network error.

Do you know what could be causing these errors and what the fix would be? If there is any other information you would like (npm-debug.log?), please let me know.

We would like to use this promising tool (and, possibly, provide some patronage if it can be used on our projects) but until these bugs are fixed, we must stop our research on it.

**Comment by ipselon** [comment]
@radman-x I really appreciate your evaluation of Structor. Thank you. 
As for your errors, I'm not a guru in node.js and npm ecosystem, but I'll try to explain what reasons  errors have as it seems to me:
* `gyp WARN EACCES user "root" does not have permission to access the dev dir ` to overcome this error you may refer to this issue https://github.com/nodejs/node-gyp/issues/454
* `POST http://localhost:2222/invoke net::ERR_EMPTY_RESPONSE(anonymous function) ` if you have issues in your local network, please try the second way of "cloning" a boilerplate from StructorMarket:
    * donwload a package of a boilerplate from StructorMarket
    * unpack it somewhere on your local machine
    * go to appeared directory
    * run command `npm install`
    * run command `structor`

**Comment by radman-x** [comment]
Update: we reverted back to Structor v0.2.2 (but still keeping node v5.3.0) and were able to again successfully install and use Structor. Actually, we needed to use this version of the Bootstrap prepack (the normal master version did not work):

https://github.com/ipselon/bootstrap-prepack/tree/7ea688cdcba04f8974abd91b2e5b9595c8732701

Also, we continued to get the "root permission" warnings similar to the v0.2.6 install but none of the errors.
We are now able to create custom component including external component by modifying index.js which helps us integrate into our dev process. Some of the errors we found before were traced down to errors on our part (e.g., not always putting thead under a table, etc.).

When I get a little time, I will review the node-gyp issue you refer to and roll forward to Structor v0.2.6 using the "second" approach to installing the prepack. Also, we will now re-start trying to use Structor in our dev process.

**Comment by ipselon** [comment]
The major change in version 0.2.6 is in using Babel 6. And I'm sure that 0.2.2 version will cause many issues with projects on StructorMarket because they are updated according to the lates version of Structor, not saying that you can miss all further improvements.
As an option to check if your system (node.js + npm + OS) is working with Babel 6, you can try to build some node.js app using Webpack + Babel 6 + React Bootstrap + Express without Structor at all.

**Comment by radman-x** [comment]
Your suggestions re: node-gyp and second way of "cloning" worked well. We now have Structor v0.2.6 up and running and can create custom components. For future readers, while there are many suggestions in the link above re: the node-gyp fix, we just used the following:

      sudo npm install --unsafe-perm --verbose -g structor

("--unsafe-perm" is important, but not sure the "--verbose" is really needed).

We still hit an error in jquery when creating a component but if we just continue in the debugger everything seems to work fine. Also, we are still getting the error from issue #32 as reported by @adambro.
But this is good progress.

**Comment by radman-x** [comment]
Update: Here is the exception error we are getting when we create a custom component -- it occurs after the last step in the wizard (we created both a new group and new component here):

<exception>: TypeError: Cannot read property 'opener' of undefined at wb (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:18084) at xb (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:18226) at Function.n.extend.css (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:22479) at http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:23460 at n.access (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:2:30270) at n.fn.extend.css (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:23301) at n (http://localhost:2222/structor/main.js:71:21619) at Object.r.refresh (http://localhost:2222/structor/main.js:71:26159) at r (http://localhost:2222/structor/main.js:71:25416)
message: "Cannot read property 'opener' of undefined"
stack: "TypeError: Cannot read property 'opener' of undefined↵    at wb (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:18084)↵    at xb (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:18226)↵    at Function.n.extend.css (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:22479)↵    at http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:23460↵    at n.access (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:2:30270)↵    at n.fn.extend.css (http://localhost:2222/structor/assets/jquery-2.1.3.min.js:3:23301)↵    at n (http://localhost:2222/structor/main.js:71:21619)↵    at Object.r.refresh (http://localhost:2222/structor/main.js:71:26159)↵    at r (http://localhost:2222/structor/main.js:71:25416)"

We are able to just continue in the debugger and everything seems to work fine (so far).

**Comment by ipselon** [comment]
Could you elaborate on what is debugger in which you are running structor?

**Comment by radman-x** [comment]
Chrome Version 47.0.2526.73 beta (64-bit)

**Comment by ipselon** [comment]
In what else browsers you've tried Structor?

**Comment by radman-x** [comment]
We do most of our dev in Chrome. But here are some other browsers we tried:

Firefox v33.0.2:
Got following warnings when loading project:
"Warning: Failed propType: Children will not be rendered for dividers Check the render method of `TestToolbarComponent`." bundle.js:4888
"Warning: Failed propType: The prop 'id' is required to make 'Dropdown' accessible for users using assistive technologies such as screen readers Check the render method of `Uncontrolled(Dropdown)`."

Above warnings also are repeated when creating custom component (simple wrapping of Bootstrap button) and whenever page is refreshed. However, we did NOT get the jquery error thrown (nor any other errors).

Safari Version 6.1.1 (8537.73.11)
Same results at Firefox.

Also, thinking this might be due to the beta version of Chrome, I upgraded to the following:

Chrome Version 47.0.2526.106 (64-bit)

But still get the same jquery error as the Chrome beta version. Also, we are getting the same warnings as described above for FireFox and Safari (may have been getting those on the beta version, too).

**Comment by Bartekus** [comment]
FYI, you should never install any package manager with sudo, this especially applies to npm.
Please look into fixing the npm permissions by following this official guide: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by radman-x** [comment]
Thanx @Bartekus for this suggestion. We fixed those permissions and now have installed the latest Structor without using sudo.

**Comment by radman-x** [comment]
@ipselon -- Have you been able to re-create the JQuery exception I documented above? Have you tried this in latest Chrome debugger? This occurs every time we create a component. We even get it when just creating creating a very simple component around a <div> and storing it in the Widgets group (ie, no custom group). Also, we get it with the latest version of Structor (v0.2.7) and after re-installing this using @Bartekus suggestion above.

**Comment by radman-x** [comment]
Also I changed the title of this issue since the sudo install problem is now fixed.

**Comment by ipselon** [comment]
@radman-x I've not met such error in Chrome, Firefox or Safari on Mac OS X. So, if you try to use some build of Cromium, I have no idea what happend in that case.

**Comment by ipselon** [comment]
I have to close this issue since it was resolved.
