### ISSUE TITLE
Fails if starting with an existing `node_modules` directory.

### ISSUE THREAD

**Issue by mic159** [ipselon/structor#36]
I didn't want to install structor globally with `npm install -g`, so I thought it was only appropriate to install it inside the empty directory I was going to use.

```bash
mkdir structor-test
cd structor-test
npm install structor
./node_modules/.bin/structor
```

But unfortunately structor is confused and gives me an error:
`["Error: Directory /home/michaelc/code/structor-test does not have package.json or node_modules."]`

It would be nice to be able to do this, It was quite confusing for a while there.

**Comment by ipselon** [comment]
@mic159 try to start with option `-d` where specify absolute path to the current directory.

**Comment by mic159** [comment]
Same error.

I want it to show the gallery even when there is already `node_modules` in the project directory.
So that I dont have to install structor elsewhere to use it. Everything can be contained in the project directory, including structor itself.

**Comment by ipselon** [comment]
Well, you can install Structor locally and start it locally, but Structor will read the current directory (or which was specified in `-d` option), and there `.structor` folder should be. So, if you want to see a gallery you have to start structor in an empty folder or specifiy it through `-d` option.
