### ISSUE TITLE
errors when structor is installed not globally

### ISSUE THREAD

**Issue by lalop** [ipselon/structor#38]
I give a try to structor but I have this error with the last version :

```
Unknown plugin ".../node_modules/structor/node_modules/babel-plugin-react-transform" specified in "base" at 0
```
`babel-plugin-react-transform`is present in the root node_modules but not in the structor's one.

**Comment by ipselon** [comment]
Do `babel-plugin-react-transform` present in structor's package.json file?

**Comment by lalop** [comment]
yes

**Comment by ipselon** [comment]
what is the version of npm do you have?

**Comment by lalop** [comment]
I’m using npm 3.3.12 and node 5.3

**Comment by ipselon** [comment]
the structure of node lib directory should be the following:
```
lib/
    ...
    node_modules/
         structor/
              node_modules/
                     babel-plugin-react-transform/
```

Do you have the same, except plugin folder?

**Comment by lalop** [comment]
In `node_modules/structor/node_modules` I only have `esprima-fb`

**Comment by lalop** [comment]
for informationo I didn't install structor globally

**Comment by ipselon** [comment]
oh! that is different story :-) 
read this issue https://github.com/ipselon/structor/issues/36 
to avoid such a problems please install globally, there are a lot issues with babel otherwise.

**Comment by lalop** [comment]
I solved the first issue commented here by installing structor locally then launching it in a new clean subfolder :
```
$ mkdir structor-test
$ cp structor-test
$ mkdir demo
$ ./node_modules/.bin/structor -d demo
```

Structor work for me now, I'd to modify MiddlewareCompilerManager use the default npm loader and not define the file were the babel plugin are

**Comment by ipselon** [comment]
OK, but in that case structor will not work in global scope.

**Comment by lalop** [comment]
nom can’t load this package in global scope ?

**Comment by ipselon** [comment]
nope, because npm 3 installs all dependent modules under structor directory, but when structor is installed locally npm 3 makes a flat structure in the same directory where structor is, so webpack can't load dependency.

**Comment by lalop** [comment]
Isn’t webpack loading the dependencies in my case ?

**Comment by ipselon** [comment]
I might made mistake - in case of flat structure npm 3 works for webpack because it knows about node_modules in root dir. In global scope webpack doesn't obtain right path to node_modules from npm.

**Comment by lalop** [comment]
To be honest I don’t know

**Comment by Bartekus** [comment]
@lalop Please make sure that your npm is properly installed, ie. does not need sudo to install globals. Then please install the structor with -g flag since it is design to function within global context.
This software is safe and a productive piece of engineering, please use it as prescribed to avoid unnecessary problems and possibly confuse new comers.
