### ISSUE TITLE
Good documentation, weak examples.

### ISSUE THREAD

**Issue by Bartekus** [ipselon/structor#39]
Thank you for making this Alex, I feel structor might be a partial solution to the angst that developers feel regarding the rate of change in JS world in general, and React in particular. 
However I feel that while having excellent documentation, both of the pre-packs lack basic visual structure  that would make them a lot more exciting to the designers and junior programmers alike. 
Examples convey multitude of otherwise hard to explain concepts and while it's all there in your excellent documentation (both, written and video based); the fact remain that this project will pick up much bigger momentum if it can facilitate itself not only as outstanding UI/Business Logic tool, but also a learning/teaching platform. 

You have asked previously if structor is suffering from poor UI design/implementation and I can with certain level of confidence assure you that isn't the case, however for the reasons mentioned above, people are not as eager to adapt it as they otherwise would be given strong marketing potential a visual examples can promote. 

As far as what I'm proposing here: a basic 2 page structure with header(nav + link to the other page), body and footer. It could be a basic landing page/about page for the structor, used as both, form of showcase and case study.

Again, thank you for your hard work Alex, I really dig this project and I will be contributing to it from here on. Perhaps I'll submit what I'm proposing after all ;)

**Comment by ipselon** [comment]
@Bartekus thank you very much for your kind words, I really appreciate your feedback. I totally agree with you that Structor and its eco system have to have more educational materials though some docs I've tried to accomplish by myself. 
Even so, having discussed a lot about features which should be added/modified or missing ones, I'm busy with making this tool more suitable to create a real word application. I'm going to make a service which allows to install different generators as addons and not so complex as existing. Additionally, there will be boilerplates of projects with predefined REST application with HATEOAS, and some generators will generate full-fledged components according to REST interface metadata.
So, taking in account that I should accomplish all these plans alone, I really appreciate your contribution to this project. And if you have any idea of how to make the learning process easier it will be awesome.

**Comment by Bartekus** [comment]
@ipselon that's absolutely brilliant Alex, I think you are addressing the most crucial aspects that the JS community is facing and I'm glad I have taken a deeper look into structor and discover the incredible potential that it can facilitate as visual bridge between abstract code and graphical elements that correspond to it. I'm working on bringing few different yet powerful ideas from within JS community, mainly an expanded 3ree framework in docker form as to ease the access to general public. I honestly couldn't imagine a better tool than structor to drop into the stack, further complementing the incredible power that react-redux-rethinkDB-babel-express-lodash and finalizing it with structor. The framework will be called r3bels so I don't think it a coincident that I finally gave in and tried structor, it a perfect last piece of the puzzle I've been collecting. I must say, for all the cries of hardship that I hear from the community, I certainly feel very excited about the future that awaits javascript as a whole.
Is there a particular color theme that you picture we should dress r3bels in? I'm thinking blue and orange or blue and yellow, what about you?

**Comment by Bartekus** [comment]
As to facilitating educational materials, I'll try to put a comprehensive medium blog post about it, however I'm still very much so a newbie when compared to the likes of yourself and other pioneers of the open software community, so it will take me some time to learn structor enough to be able to teach it. But I'm confident I can do it, so it shall be done!

**Comment by Bartekus** [comment]
@ipselon Also I have to ask you one last thing, are there any specific gotchas that I should be aware of, when attempting to integrate https://github.com/anorudes/redux-easy-boilerplate into structor?

**Comment by ipselon** [comment]
Perfect, an article on Medium is what I've asked in our Facebook group, that will help to popularize Structor and its philosophy in community. 

As for `redux-easy-boilerplate`, at the first glance there may be some issues: structor works only with react-router v1.0.x (till React Router 2.0.0 will be out), also take a look on `.structor/webpack.config.js` to add needed loaders. And of cause if there is aloready some custom components except React Bootstrap add them into `.structor/src/index.js` There is my observation of this so far...

**Comment by Bartekus** [comment]
Excellent, that should be enough to get me going, I'll keep you posted on my progress and should I need further assistance.

**Comment by Bartekus** [comment]
Hello again Alex, 
I've got a proposition that I'd like you to consider as I'd like you to on board of a new open software initiative:
Under Araphel.org, an esoteric conclave would be established to oversight an OSI project called R3Stack (R3Stack.com is the stacks url)

Our main component is currently being finalized by Matt Krick with his Meatier development. 
Basically it's a meteor-like stack build within react-redux-rethinkDB specifications, you can check it out here: https://github.com/mattkrick/meatier

We are now in preliminary talks with OpenCredo which would be providing the front end https://github.com/opencredo/opencredo-react-boilerplate 

Finally we would love to have you on board of the project as we see Structor as indispensable aid and powerful tool in teaching children that would complement and finalize the entire stack.

So the whole thing will either be entirely docker based as to simplify the installation/operation/deployment or we could utilize AZK as binding agent/control agent (tho since itself is also docker base it could be entirely unnecessary, however all this is open to discussion)

The reason for this stack, is to create a framework which unlike other frameworks, do not lend itself to be ridged and unchanging but rather continually evolve with community while providing kids with the best practice, that are always current and reflective of the react community; an full-spectrum solution with emphasis on functional programming.

Our aim would be to providing the best structure for learning by allowing kids to look at the current development practices, while at the same time having entire build for reverse engineering purposes as it is our belief that by such example the widest segment of differentiating potential that kids have could be sparked and nurtured.

By setting an ever evolving standard we can bring balance to the fractured and disjoined react [force ;) ] community and at the same time support the good practices while discarding unwanted ones.

The structure of Araphel.org in a way like that of a philosophical branch of the anonymous movement and itself will be in form of a round table, where each member does his best to express and contribute in whatever capacity they can while at the same time setting an example and nurturing community in general. We will essentially create by hackers for hacker - build-break-learn stack.

What would you say to that?

**Comment by ipselon** [comment]
Hi @Bartekus! I'sorry for late response, was busy. I've read your proposition and was trying to answer you by mail but didn't find e-mail address. Finally your comment was deleted somehow :-). 

It would be very exciting and challenging to work with you and your team, I think you guys are doing a great framework/tool, and especially this is great to me because you've chosen my project to be the part of your framework. 

I thoroughly pondered your proposal and have to say that I can't join your team because of two reasons. The first is that now I'm working on the second part of our project - a on-line generators for UI components which will be connected to a REST service in a Web application. The second part is that I have a colleague with which I founded a company/startup, and now we are on a half way of launching this company officially.
Taking in account all these I phisically would not able to participate in your project.

But, of cause I would like to help you, or if you have any ideas how to improve or change structor I'll be glad to do that.

Thank you!

**Comment by Bartekus** [comment]
Hello @ipselon,

Please do not be sorry Alex, you are doing amazing work and I certainly can't ask of you to do more, in fact I didn't feel right about that request in the first place so I took it down. It's quite evident how amazing your contributions to the react community are and I for one feel quite obligated to help out with Structor in any capacity that I hold. On top of that I truly think that Structors hold potential to facilitating web development in ways that no other tool that I've ever been exposed to can. Bridging the gap between designer and developer is not an easy task and the fact that Structor does it and does it so well, seems magical to a lot of people. Furthermore while I absolutely understand and agree with your decision I also hope that you won't mind us going ahead and including Structor in the r3stack as I simply can't imagine not having it in a stack that's directed towards learning and teaching. This is especially true when it comes to kids who in general are very observant and capable of much more when they can interact with a problem versus just devise a solution. So again, please do not feel bad, we share a vision of better web development and even tho we can't work directly together, the path of Structor and r3stack as I see it are mutually beneficial and aligned. 

My first contributions will be most-likely be in the aspects of updates, at least until I get more comfortable with my skills, but as that improves, so will the scope and the range of my contributions!

Again, thank you for all your hard work Alex and talk to you soon, I should have something to contribute soon enough! 

Cheers and ttyl!

**Comment by auvipy** [comment]
@Bartekus @ipselon I'm an experienced django/rest backend developer and a fed-up-half-backed front end guy. I'm now seriously devoted to learning react/redux and their best practices to use them seriously on the front end of my REST back ends. I have considered using structor as my prototyping and learning tool. I would be very happy to contribute back in this project too. both of your inputs/directions will be great to proceed.

**Comment by Bartekus** [comment]
hey @auvipy,
If you would like, I'm organizing a react-redux community as the intend is to have by-hackers-for-hackers stack and code practice. The stack is called r3stack and the community is called Araphel
We are still very much so in infancy but are very open at this point to anybody who wishes to learn and thru sharing of their knowledge contribute to the greater good of people all over the world.
At the core we are somewhat altruistic and esoteric, but if that is ok with you, send me an email <bartekus@gmail.com> and I'll send you an invite. 

However do not feel obligated to, and if you wish to learn redux-react, the first thing is:

This one is free: [this is a must, a redux-bible if you will]
Getting Started with Redux
https://egghead.io/series/getting-started-with-redux

then if you can get, get this: [is normaly 29$ but it's on sail now for 10$ and is worth 10x more really]
Modern React with Redux | Udemy
https://www.udemy.com/react-redux/

These two alone will cover most of everything, I give you my word on that.
Let me know when you thirst for more.

**Comment by auvipy** [comment]
hey I will certainly say hi and interested to get involved! my mail: auvipy@gmail.com

**Comment by ipselon** [comment]
I'm closing it because the recent version has possibility to create components presets with example pages.
