### ISSUE TITLE
package.json refer to thirdparty/react-widgets-master

### ISSUE THREAD

**Issue by jiixing** [ipselon/structor#4]
"react-widgets": "file:../../thirdparty/react-widgets-master",

is it using a patched version of the react-widgets library?

**Comment by ipselon** [comment]
No, it was used from github repo because of react-widgets with react 0.14 still is not published on npm.

**Comment by jiixing** [comment]
I fixed it by replacing the line with

    "react-widgets": "git://github.com/jquense/react-widgets#6ec06b8",

**Comment by ipselon** [comment]
will you make PR ?
