### ISSUE TITLE
Supporting Fluxxor

### ISSUE THREAD

**Issue by zzj1213** [ipselon/structor#40]
Can support Fluxxor.com ?

**Comment by ipselon** [comment]
Each projects boilerplate can be modified to use any type of Flux architecture, if you are familiart with Redux you easily can modify any of exisiting projects for Structor for Fluxorr (I guess). 

But, of cause generator for Redux component should not be used in that case.

**Comment by Bartekus** [comment]
@zzj1213 Supporting a Fluxxor would be counter productive as Redux is clearly a forefront champion of the flux architecture. The fact that Facebook hired the man behind the redux architecture (Dan Abramov) to become one of the key drivers of the react movement should be a convincing enough for anybody who objectively looks at the situation.

**Comment by auvipy** [comment]
I would stick with redux!!! it simply rocks and blow others!!! @zzj1213

**Comment by the-simian** [comment]
I think using redux was the right choice.

**Comment by ipselon** [comment]
Technically you can use any Flux implementation with Structor. In order to avoid using Redux you have to remove storage initialization in file `.structor/src/default.js`

Just remove lines:
```javascript
import storeManager from '../../src/client/store/storeManager.js';
...
const store = storeManager();
```

**Comment by auvipy** [comment]
https://github.com/mobxjs same applies for using mobx?

**Comment by ipselon** [comment]
@auvipy yes, the same.
