### ISSUE TITLE
Undo broken

### ISSUE THREAD

**Issue by jamesdwilson** [ipselon/structor#42]
First experience with Structor.. the app loads in the editor, I click a component, I click backspace. It erases all of App. I click undo, and it does nothing.

**Comment by jamesdwilson** [comment]
Good news, I can't replicate this.. maybe an edge case

**Comment by ipselon** [comment]
When you clicked backspace in browser previous page is opened, and structor catches this when focus is in workspace. But if focus is not in workspace browser opens previos page.

**Comment by ipselon** [comment]
I think I can close it.

**Comment by jamesdwilson** [comment]
I know what you're talking about, but that wasn't it. I'm a web developer for over 15 years. This is not the backspace page navigation bug. This deleted an item from the page, I think it was an App tag, and then it refused to undo it.
