### ISSUE TITLE
External code tree, expose Structor's internal WebPack configs?

### ISSUE THREAD

**Issue by radman-x** [ipselon/structor#44]
We have been experimenting with Structor a lot over the last few weeks and it continues to look very promising. However,  we need a way to access a large external source code tree whose dependency tree we cannot modify by putting it under Structor's /src/client/components, etc. Also, because of its size, we cannot add everything into Structor's index.js file, like you suggest in the documentation.

Normally, we just modify WebPack's config file and include resolve.root or resolve.moduleDirectories and this does work when we build with Structor's webpack-config.js (which we modify for this).

However, when editing, Structor runs an internal, programmatic invocation of WebPack that we have no access to so we cannot set these configuration properties.

Do you have any suggestions for how to handle this? Does it make sense to expose the internal WebPack configs (or at least the resolve.root/moduleDirectories)?

**Comment by ipselon** [comment]
@radman-x try to include your configuration into `.stuctor/webpack.config.js`. 

Otherwise you may fork this repo and change `src/server/src/MiddlewareCompilerManager.js` as you need.

How large is your component tree?

**Comment by radman-x** [comment]
Thanx @ipselon -- that largely worked. We inserted resolve.root="path_to_external_tree_root". Only problem is that the presets in MiddlewareCompilerManager.js do not use paths. This is required, see:

[http://stackoverflow.com/questions/33538403/error-couldnt-find-preset-react-when-installed-using-npm-install-global-ba](url)

So we modified MiddlewareCompilerManager.js by replacing line 64 with:

        presets: [
            path.join(this.sm.getServer('nodeModules.dirPath'), 'babel-preset-react'),
            path.join(this.sm.getServer('nodeModules.dirPath'), 'babel-preset-es2015'),
            path.join(this.sm.getServer('nodeModules.dirPath'), 'babel-preset-stage-0')
        ],

And now everything works. Would you like me to do a PR for this?

**Comment by ipselon** [comment]
I'm glad that you resolve your issue, but, this is not issue for others :-). So, PR is not needed, `.babelrc` serves to resolve babel presets.

**Comment by radman-x** [comment]
Are you referring to the .babelrc under the pre-pack folder or the one under the Structor global npm install folder? We could not get this to work modifying the one under the pre-pack folder, only by modifying MiddlewareCompilerManager.js. Plus, I think some of your other users may have large external source code trees :-)

**Comment by ipselon** [comment]
@radman-x different settings of node and npm lead to such issues, and you might be right that Structor's webpack config has to define paths to libs implicitly.

I leave this issue open till I test such a config in new version of Structor.

Anyway, thank you for your contribution, I'll not find out babel's issues with Structor by myself.

**Comment by radman-x** [comment]
OK, thanx. We are trying to avoid having to modify Structor, if possible.

**Comment by radman-x** [comment]
And this is not urgent as your first suggestion helped a lot and the modification to Structor is very minimal.

**Comment by Bartekus** [comment]
problem might be a little bit related to .babelrc as it's presence in the directory structure will override and take precedence over any other source of setting for babel at the level of the .babelrc file and all sub-folders under it. The only way to avoid trickling down of the the settings from the higher positioned .babelrc file is to put another .babelrc file where the new setting are to be applied... I'm sorry, I'm not the best at explaing this but I hope it can provide some ideas if it's in fact related to this problem.

**Comment by ipselon** [comment]
@radman-x @Bartekus I bumped new version https://github.com/ipselon/structor/releases/tag/v0.2.8 where included proposed chages. Thanks.
