### ISSUE TITLE
Structor behind Apache 2.2 proxy

### ISSUE THREAD

**Issue by dmk23** [ipselon/structor#47]
I want to run Structor on server to be able to share it between multiple users to collaborate. I have set up Apache VHost to expose the service externally -

```
<VirtualHost *:80>
    ServerName mydomain.com
    SetEnv force-proxy-request-1.0 1
    SetEnv proxy-nokeepalive 1 
    SetEnv proxy-initial-not-pooled 1
    ProxyPass           / http://localhost:2222/structor/
    ProxyPassReverse    / http://localhost:2222/structor/
</VirtualHost>
```
However when I try to go to the service I see the following message -

![image](https://cloud.githubusercontent.com/assets/1828444/13307900/ba00f730-db23-11e5-98cd-bacb827d3490.png)

I tried changing everything imaginable, including directory permissions, upgrading to the latest Node and downloading bootstrap boilerplate per instructions. Nothing seems to work and I am not even sure if/where there are any logs I could review.

Could you help figure this out?

**Comment by ipselon** [comment]
@dmk23 as far as I don't have devops capabilities as I wish, and not sure I can help you. Though this can be helpful, structor should have 3 http endpoint:
* `http://localhost:2222/structor` (for structor itself)
* `http://localhost:2222/absolute path to .structor/desk folder/__build__`  (for webpack dev middleware)
* `http://localhost:2222/webpack-hot-middleware/client?path=/absolute path to .structor/desk folder/a`  (for webpack dev middleware socket)

**Comment by ipselon** [comment]
@dmk23 did you manage to run Sturctor behind Apache proxy?

**Comment by dmk23** [comment]
Sorry did not re-test that... I managed to access basic Structor by exposing the port without the Apache proxy - but found too many things in the latest release broken outright to consider using it...

Will be prototyping React by hand for now - my key issue is how to build applications with Django REST backend - which is another thing I'm not clear how to do with Structor...

**Comment by ipselon** [comment]
OK, so I can close this issue. 

@dmk23 also, we introduced new brand feature - online generators. So, if you want or your team we can create components right for your project with back end, and you will get them through installable generators. Look ant our site https://helmetrex.com
