### ISSUE TITLE
Only 2 generators available.

### ISSUE THREAD

**Issue by theanthonyplan** [ipselon/structor#48]
I have a quick question regarding the component generators.  About a month ago, my build of structor provided the full set of 4 generator options for the bootstrap-prepack ( which can be seen [at this queued frame from your Auth video tutorial](https://youtu.be/Ks2tWAJvDqo?t=41s).), but now only the first two generators are available.  I would estimate that they went missing sometime in the last month or two, and I had not updated or modified any of the node_modules during that time.

Today while troubleshooting, I rebuilt structor a few times (inside of a fresh environment), but the issue remains and I see no signs of failures or errors being reported.  I tried installing the latest version from npm, and installing manually from the prepack seems to be no different.

Any ideas what it is that I might be doing wrong?  I suspect that one or more of structor's dependencies may not have been installed properly, but at this moment I have too little evidence to substantiate that theory.

Thanks again for all your phenomenal work, Alex.  This is truly an amazing project-- its made my web development enjoyable again.

**Comment by ipselon** [comment]
@theanthonyplan Ah, this is my fault but not structor's issue. Those two generators (Authentication social menu and Social account info panel) where the probe to make me sure that such generators will be useful. And in the last release of structor and its projects I removed them at all from projects.

Fortunately, soon we start new brand site with on-line generators for Structor, where you can choose and  install those and many other generators right into your particular project. So, please wait for new version of Structor and Structor Market.

Tanks for your appreciation.

**Comment by theanthonyplan** [comment]
Cool, if they're depreciated then my issue is not really an issue at all.  That's great news, definitely looking forwards to that update and all its new features.

I'll have to make my own auth component eventually anyways, but I was wondering if there was any chance that you could point me in the direction of the source code for the old generators (or the source from the tutorial)? But only if its already readily available, its definitely not urgent enough for me to ask you to go hunting down old docs. 

Thanks again for your help, I'll close this issue down.

**Comment by ipselon** [comment]
@theanthonyplan download the source code archive from here https://github.com/ipselon/bootstrap-prepack/releases of release v0.0.2 and find generators in `.structor/generators` folder, then just copy them into the same directory into project you are working now.

**Comment by theanthonyplan** [comment]
Awesome I owe you yet again, thanks a ton.
