### ISSUE TITLE
Redirect Question & Feature Request

### ISSUE THREAD

**Issue by theanthonyplan** [ipselon/structor#49]
Sorry for opening this under issues, neither one of these points are actual issues.

Like always, I'll start off by saying that Structor is phenomenal software and that I'm been having a great time using it.  

**I had a question about request redirection**-- I thought I saw something in a commit regarding some redirect code, I was wondering if this is a new feature?  While writing an auth flow for JWT I ran into the problem of needing to do a conditional redirect.  I presume that there would be multiple ways to implement redirection, but I was wondering if  you could prescribe a "best" way to approach this.  I was thinking about using react-router to call either router.tranisitionTo() or history.push() -- although I am uncertain as to which one of those objects/calls would be appropriate for use with Structor.  Any help or insight you can provide would be greatly appreciated.

**Additionally, I had an idea for a simple feature:  Class Regrouping**
Often while managing my projects in preparation for an export I will consolidate all my components into a single project-specific group.  I think there may already be a way to do this that I've somehow lost track of-- my current workaround involves creating dummy components in the new group and then copying over the source.  

I just wanted to pass along this idea -- my little way of helping contribute to the project for now, definitely NOT a complaint or demand by any means.  Very low urgency behind this, and I only suggested it because it seemed like a feature that could, in the proper hands, be implemented without much complexity.  

Thanks again for your time and efforts!
avg

**Comment by ipselon** [comment]
@theanthonyplan Thank you for kind words and for using Structor. You may write anything here, I appreciate any issue.

1. I wrote some brief notes about how to use React Router in a Structor project. Please, take a look here: https://github.com/ipselon/structor/wiki/Using-React-Router-inside-of-components Also, if you find any mistakes in my English, please fix them.

2. An idea with exporting and importing of dummy components is brilliant, thanks. I need to think thoroughly about this. Maybe I will implement something like preserving a component or some composition of components in the cloud, and a user can retrieve it into another project. Something like that...

**Comment by theanthonyplan** [comment]
1. Perfect, this is the exact info I was looking for.  

2. Wow a cloud-based solution was way more comprehensive than what I had in mind, that would be especially great for managing components across projects.  I also forgot to mention, to make sure that the new component group (and initialStore.js) has all the hookups and references it needs I always make sure that I provide the first "half" of the generator metadata-- stateToProps, any handlers, and reducerRoot--  when creating the dummy components.  I've found this to be the most reliable way of _informing_ the project environment of the code that is about to be pasted in.  

I'm sure you are already well aware of all of this and know the proper way to handle it under the hood, but I just wanted to note it for anyone else that might stumble upon this thread.  

Thanks again for your work and as I read through the docs I'll definitely keep a helpful eye out for any edits.

**Comment by ipselon** [comment]
@theanthonyplan thanks a lot.
