### ISSUE TITLE
Proxy server error connecting to localhost:3000

### ISSUE THREAD

**Issue by maarekj** [ipselon/structor#5]
Hi,
When I run structor command in my directory, structor is started, but there is the following error:

```
 $ structor
Structor started successfully.
Please go to http://localhost:2222/structor
webpack built 5c0bfebb7ef316e5791f in 9941ms
Proxy server error connecting to http://localhost:3000/rbs/getProjectGalleryList
```

When I go to **http://localhost:2222/structor**, I see the interface, but the component <ProjectList /> show this error: *Error occured: TypeError: Failed to fetch*

see the screenshot.
![screenshot](https://dl.dropboxusercontent.com/u/9704388/forum/Capture%20d%E2%80%99%C3%A9cran%202015-10-23%20%C3%A0%2010.20.48.png)

**Comment by ipselon** [comment]
This is because the current project has components which make requests to http server. You can find server exactly in the project's folder ```server.js```. To avoid this error please run command in the project's directory: ```node ./server.js```

**Comment by maarekj** [comment]
Works, thank you.
