### ISSUE TITLE
keep getting "Failed to fetch [...]" error

### ISSUE THREAD

**Issue by devboell** [ipselon/structor#50]
Hi,
 
  I followed the instructions (npm i -g structor, mkdir testdir, cd testdir, structor), but every time I try to clone the bootstrap-prepack I get this error: Failed to fetch [...]

  I have then tried to restart the structor server (^C, structor) and get different error msgs, like:

- `Unknown plugin "transform-runtime" specified in "/Users/myhome/Dev/Experiments/structor/tmp2/.babelrc" at 0, attempted to resolve relative to "/Users/myhome/Dev/Experiments/structor/tmp2"`

- or (I didn't copy/paste this one):
  cannot find package.json or node_modules

- and another one saying something about a folder being corrupted

On three different attempts, three different error msgs after restarting structor. All three attempts had the same initial error (Failed to fetch [...])

**Comment by ipselon** [comment]
@devboell there is an issue with npm 3 installation process, but it seems that 3.8 version makes installation quick a lot.

But, in your case I would try the second way: download package of bootstrap-prepack repo to local host, unpack it, enter into that directory, run `npm install && structor`

**Comment by devboell** [comment]
ok, thanks - the second way works

**Comment by ipselon** [comment]
Glad to hear it, so I'll close this issue.
