### ISSUE TITLE
Drag-and-drop components

### ISSUE THREAD

**Issue by isaacdalmarco** [ipselon/structor#51]
Hi @ipselon, I would like to suggest you to implement the drag-and-drop function to the page builder, it would makes it easier to work. 

This is an example of other page builder: http://www.layoutit.com/build

Congratulations and thank you very much for this contribution.

**Comment by ipselon** [comment]
Hi @isaacdalmarco, sorry for late response - was busy with new release. Taking in account what I made in new version of Structor, could you try and tell if you still need drag & drop?

**Comment by isaacdalmarco** [comment]
It is much better than before, but I still think it could be more productive with the drag and drop. Mainly when we need to modify the position of the components. But it is up to you.

Thank you again.

**Comment by ipselon** [comment]
OK, thank you for your interest, I hope new UX in Structor will be productive as well as drag and drop.
