### ISSUE TITLE
Docs, demo, example

### ISSUE THREAD

**Issue by behind2** [ipselon/structor#53]
Hi,I am sorry. I just want to find some examples or demos to learn your library. Could you give me ulrs of tutorials.

**Comment by ipselon** [comment]
@behind2 Unfortunately, what you see in Readme is all what we get to understand what is Structor. BTW, this is not a library, this is a visual UI builder for React Web applications.

**Comment by behind2** [comment]
aha, I seemly understood! Tks. I get down to read again.
