### ISSUE TITLE
Error 301 in main generator

### ISSUE THREAD

**Issue by tarikmlaco** [ipselon/structor#55]
I tried generating prepack as you said, I tried using the structor generator, created an empty folder, started structor on localhost:2222, but the error message says 
```
["Got error code 301 processing request to http://helmetrex.com/structor/invoke"]
```
...is the server down, or is it related to the structor itself?

**Comment by ipselon** [comment]
Did you go to adress http://localhost:2222/structor ? or just http://localhost:2222 ?

**Comment by tarikmlaco** [comment]
localhost:2222/structor...it says on the main screen

**Comment by ipselon** [comment]
good, then what exactly you did, just elaborate on steps you did.

**Comment by tarikmlaco** [comment]
```
$ npm i -g structor
$ mkdir structor-project
$ cd structor-project
$ structor
```
Then i went to localhost:2222/structor and the errror message was
```
["Got error code 301 processing request to http://helmetrex.com/structor/invoke"]
```

**Comment by ipselon** [comment]
that is strange error, Structor server REST api is exposed through the endpoint
```
http://localhost:2222/structor/invoke
```

I could not understand why you was redirected to http://helmetrex.com, even not to https://helmetrex.com

Do you have everything OK in dns or hosts configuration ?

**Comment by ipselon** [comment]
Could you tell what OS you have an browser ?

**Comment by tarikmlaco** [comment]
Mac OS X El Capitan....Chrome 49

**Comment by ipselon** [comment]
Same as me :-)

**Comment by tarikmlaco** [comment]
:) and I haven't changed anything regarding DNS or hosts, I don't think that's supposed to be an issue...

**Comment by ipselon** [comment]
Well, and what is node and npm versions? It seems that Structor will work only with npm 3.8.x

**Comment by tarikmlaco** [comment]
node v. 5.7.1, 
npm 3.8.6.

**Comment by ipselon** [comment]
![image](https://cloud.githubusercontent.com/assets/11865795/14782561/d86054ba-0af2-11e6-958e-71d2608c80ea.png)

**Comment by ipselon** [comment]
Here what was happened when I made your steps, starting from installation
Also, 404 error - is because Structor tries silently to authenticate your account, but this is not critical error

**Comment by tarikmlaco** [comment]
I see....here's what I'm facing...
<img width="1280" alt="screen shot 2016-04-25 at 13 37 16" src="https://cloud.githubusercontent.com/assets/8452181/14782648/eea700dc-0aea-11e6-903d-759a3e37c216.png">

**Comment by ipselon** [comment]
Oh! You have an old version of Structor... try to uninstall completely
```
npm uninstall structor -g
```
and then install new one :-)

**Comment by tarikmlaco** [comment]
I installed it today...i uninstalled it now, ran npm i -g structor again...still the same version...should I pull it directly from git then?

**Comment by ipselon** [comment]
I think it would be better, if you go to your node directory and find where `structor` dir is, then just remove it completely (delete it). 
I have it here:
```
NODE_HOME/lib/node_modules/structor
```
And then install structor again with `-g` flag

**Comment by tarikmlaco** [comment]
I did...now structor is completely broken... :(
```
module.js:341
    throw err;
    ^

Error: Cannot find module './server/controller.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/tarik/.nvm/versions/node/v5.7.1/lib/node_modules/structor/structor.js:22:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
```
Also, before I deleted it...I installed structor from git, and it still said 0.2.7.
Now I can't install structor at all...

**Comment by ipselon** [comment]
It seems that you have two nodes though :-) 
Ok, I did make release of structor on github only few hours ago, if you know how to install structor from git, please do it.

**Comment by tarikmlaco** [comment]
I did exactly that...
```
npm i -g structor@https://github.com/ipselon/structor.git
```
...I assume it is a problem with my configuration, since I installed some things using brew, some using npm...maybe there's a node conflict of sorts...
Is there another way to do a fresh installation of structor? Should I maybe clone it instead of using npm?

**Comment by ipselon** [comment]
Aha, download release from here, unpack it somewhere, then build
```
npm run build-server
npm run build-client
```
go to parent directory, and install structor again
```
npm install ./folder_where_you_unpacked -g
```

**Comment by tarikmlaco** [comment]
Finally got it to work :) Sorry it was an issue with my configuration..but thank you very much for help :)

**Comment by ipselon** [comment]
You are welcome. Try to create generators...
