### ISSUE TITLE
Bulk library install

### ISSUE THREAD

**Issue by psachs21** [ipselon/structor#60]
I've been looking at Structor for a few days and despite some UI weirdness and missing docs, I think it's got a fair amount of promise. One of the things I'd like to do is take my existing component library and install it. All my components have declared prop types so there should be a way to generate metadata based on that. I don't want to have to create a generator for every component in the library.

Am i missing something or is there no way to do this?

**Comment by ipselon** [comment]
@psachs21 there is an easy way to install your own components into Structor components library:
* All your components should be copied into subdirectories and uses the same structure as all other components which are inside of seed project. To see the compatible structure just generate a couple of components using generic generators (dump component and container component with actions and reducer).
* Find `.structor/src/index.js` file and add all your components to some group or new one. Take as example generated components you made in first action (above).
* Also, if your components have actions, sagas, and reducers you have to add them manually into `actions.js`, `sagas.js` and `redusers.js`. Again, you may take as the example already generated components.

I'd much appreciate if you tell what weirdness you noticed in UI, I'll try to remove or change it. Thank you in advance.

**Comment by psachs21** [comment]
Thanks for the quick response @ipselon.

Ah i see what you mean at .structor/src/index.js, yes that would make it much easier to import my components. 
The only thing I have to figure out is a better way of associating default metadata to these components. I would like to be able to define those beside the actual component, and not in this prepack (which would hopefully remain quite static once associated to my library.) It may have to be done through a build script that copies them from the library. 

The weird UI is probably just me getting used to the copy/paste heavy interactions. Though I would suggest integration react-router in the home page. That way you can refresh the page while in the generator creation wizards without losing data.

**Comment by ipselon** [comment]
As for prepack, I'm going to migrate all projects to the only one project https://github.com/mxstbr/react-boilerplate. Structor will installed not globally but locally and will be integrated into the boilerplate right during installation process (with different profiles of metadata for Material UI or React Bootstrap, or without any library). So, I recommend to get familiar with that project :-)

Copy&Paste approach is really weird in Structor, but I can't change the behaviour so far. But you can simplify it using quick addition without copying - select `+` sign on selected component on the page, and type needed component name.

I didn't get your thought about using router and generator, could you elaborate on?

**Comment by psachs21** [comment]
Sure. 

If you try to create a new component, you see a screen to select generators etc. If i refresh the page, I return the main root of the application instead of staying on that screen. A simple example, but it applies elsewhere as well. 

Also, unrelated, what controls whether I can press the new component button or not? I can't seem to click it anymore.

**Comment by psachs21** [comment]
![screen shot 2016-06-23 at 6 26 59 pm](https://cloud.githubusercontent.com/assets/11449728/16322300/27c87734-3970-11e6-8ad8-2982e3bdab50.png)

I was referring to these buttons.

**Comment by ipselon** [comment]
Ah, I see, it seems the bug. I'll take a look.

You can't create new component without selected one on the page - generator requires initial component around which it will create new one, or instead of selected :-)

**Comment by psachs21** [comment]
I wouldn't worry about the bug. I think I got my workspace in a weird state. Doing a clean co with git fixed it.

**Comment by psachs21** [comment]
So, in ```.structor/src/index.js``` I tried to do the following:

```js
const CustomLib = require('custom-lib');

...

module.exports = {
  ...
  CustomLib: CustomLib
};
```

This should work because CustomLib is just an exported object of all the components created by the library.
However, nothing shows up for CustomLib in the menu.

If i do this, however, it does:

```js
module.exports = {
  ...
  CustomLib: {
    Comp1: CustomLib.Comp1
  }
```

Any idea what's going on?

**Comment by ipselon** [comment]
@psachs21 sorry for delay.
In this version of Structor you have to use `require('path')` for including the component. And if you want to add component from lib, you need to add the following `Component: require('lib').Component`

**Comment by ipselon** [comment]
In the next version it will be changed to form where you don't have to use require directly.

**Comment by psachs21** [comment]
Ok that's good to know. Also, is there a way to create meta data defaults for these library components? All i see is the directory ```.structor/defaults/...``` and I guess if I create a Button component I need to create a Button.json?

**Comment by psachs21** [comment]
I guess my only concern is that that would imply that Type needs to be a unique type. Hopefully if someone installs this prepack, they could also install another prepack that contains it's own Button type without conflicting.
