### ISSUE TITLE
The metadata is likely doesn't work 

### ISSUE THREAD

**Issue by xhbisme** [ipselon/structor#63]
I tried to use generator to create a new component,but after I clicked run generator button, input the metadata ,It always create the same code.must I create my own generator?

**Comment by Dmytro-Medzatiy** [comment]
Hi, @xhbisme what generator do you use? Not all the generators need the metadata, only some of them. So if you use, for example, SimpleModelComponent it doesn't support metadata, but you can clone it and write your own generator that will do. You can read about it here: https://medium.com/@alex_pustovalov/structor-as-a-playground-for-react-applications-49accf4544b8#.kp4bnza73

**Comment by xhbisme** [comment]
Thank you very much @Dmytro-Medzatiy.
