### ISSUE TITLE
Previews in the editor

### ISSUE THREAD

**Issue by Diniden** [ipselon/structor#64]
When selecting components on the left, it would be incredibly handy/neat if there was a 'preview' window to show me which component I currently selected. It would also be nice if the preview window included a simple way to switch between variations (such as arrow buttons or something).

This would eliminate always needing the full blown preview covering my workspace when I want to quick browse my components for something I would like to inject. The blocking of the visual space is one of those UX experiences that breaks your thought process when trying to pick something.

The preview window should operate like the Flash (now Adbode Animate CC) library works. A small preview window that shows what library item you selected that sits above the components (or below...)

![02](https://cloud.githubusercontent.com/assets/1149487/16811328/5962eaae-48ed-11e6-8efb-024f64044ad6.png)

I would also suggest making the current cover-your-workspace preview show up if you double click the component.

This could be made possible by creating an iframe space for the preview, and the iframe could be set to have it's content scaled with transforms thus rendering correctly, but just smaller.

**Comment by ipselon** [comment]
@Diniden I decide to remove the preview at all in new version. This feature is not convenient for now because Structor is positioned as a visual editor for React components but not for Web pages. So, taking in account this a developer should use pages in Structor as preview/development space for components.
