### ISSUE TITLE
Cannot find module "./routes/routes.js" in material-ui-prepack

### ISSUE THREAD

**Issue by EyEder** [ipselon/structor#68]
I installed structor globally but run the structor with error:
`Failed to load resource: the server responded with a status of 404 (Not Found)`
then I run `npm run install` in the project folder, and `npm run build`，but I found the error:
`ERROR in ./src/client/main.js
Module not found: Error: Cannot resolve 'file' or 'directory' ./routes/routes.js in C:\Afiles\AWork\material-ui-prepack\src\client
 @ ./src/client/main.js 21:14-43`

**I can not find the routes folder and the routes.js file in this project!**
Did you forget to add these files?

**Comment by ipselon** [comment]
@EyEder Find in main menu `Export project` item, run the exporting - it will create needed files. Then you may run building process.
