### ISSUE TITLE
Error when trying to generate wrapped npm module

### ISSUE THREAD

**Issue by rodenp** [ipselon/structor#69]
Firstly I think this tool has great potential.

I am trying to create a new generator to include a wrapped npm module called react-facebook-login.
I have been trying various things to get this to work. There is an old version in the market place under Generics/Wrappers/FaceBookLogin which i created and have been trying to .modify to get to work.

The npm module has 3 directories under the root with the following files.

dist
   facebook-login.js
src
   facebook.js
   index.js
styles
   facebook.scss

The docs describe a sample.

'use strict';

import React from 'react';
import FacebookLogin from 'react-facebook-login';

class MyComponent extends React.Component {
  constructor(props) {
      super(props);
  };

  responseFacebook = (response) => {
    console.log(response);
  };

  render() {
    return (
      <FacebookLogin
        appId="1088597931155576"
        autoLoad={true}
        fields="name,email,picture"
        callback={responseFacebook} 
      />
    )
  }
}

export default MyComponent;

Which i changed to:

import React, { Component, PropTypes } from 'react';
import FacebookLogin from 'react-facebook-login';

class <%= componentName %> extends Component {
  constructor(props) {
      super(props);
  };

  responseFacebook = (response) => {
    console.log(response);
  };

  render() {
    return (
      <FacebookLogin
        appId="<%= metadata.appId %>"
        autoLoad={true}
        fields="<%= metadata.fields %>"
        callback={responseFacebook} 
      />
    )
  }
}

export default <%= componentName %>;

I created the structor dependancies as follows:

{
    "packages": [
        {
            "name": "react-facebook-login",
            "version": "",
            "copy": [
                {
                    "from": "dist/facebook-login.js",
                    "to": "react-facebook-login/dist/facebook-login.js",
                    "isImport": true
                },
                {
                    "from": "styles/facebook.scss",
                    "to": "react-facebook-login/styles/facebook.scss",
                    "isImport": true
                },
                {
                    "from": "src/facebook.js",
                    "to": "react-facebook-login/src/facebook.js",
                    "isImport": true
                }
            ]
        }
    ]
}

when i try and save and generate the preview i get the following errors in a popup box:

![image](https://cloud.githubusercontent.com/assets/5136893/18036007/b71edafc-6d61-11e6-9224-dc206a54eb35.png)

![image](https://cloud.githubusercontent.com/assets/5136893/18036025/ffd1ced0-6d61-11e6-8389-391895e45871.png)

Can you help me understand what I am doing wrong.

many thanks

Peter

**Comment by ipselon** [comment]
@rodenp I apologise for a long delay. I made a new release of Structor with now is integrated with `react-boilerplate` project. From now Structor will be installed as a tool for `react-boilerplate` - it is adopted to the boilerplate's source code structure and has many other coupling points.

From now Structor's projects should be cloned from React Boilerplate project. Thats why for your convenience I created a fork of `react-boilerplate` repo and made some changes in it for the Structor compatibility. Please find this fork here: https://github.com/ipselon/react-boilerplate

Unfortunately, there is no the ability to publish own generators so far. But I'm intensively working on this feature and it will be more convenient than it is in the previous versions of Structor.

I'll try to migrate your generator into React Boilerplate project and will give you a notice when it will be available on Structor Market.

**Comment by rodenp** [comment]
Hi Alex,
I really like the passion and commitment you have towards structor.
What would really help is more examples and more documentation about generators and how to use the template versions as well as create brand new ones.
What would especially help is more details on creating npm wrappers. I am confused about npm modules that have multiple directories. 
Could you give me some guidance on getting the facebooklogin generator to work?
RegardsPeter

Get Outlook for iOS

		_____________________________

**Comment by ipselon** [comment]
@rodenp I'm closing this issue - now there is a guide which covers a majority of what Structor can.
