### ISSUE TITLE
run success, can not visit by web browser

### ISSUE THREAD

**Issue by vanloswang** [ipselon/structor#71]
npm install structor -g and npm install its deps.
structor -p 2222 with no error reported.
Then visit from web browser, get the following content:
```bash
Cannot GET /
```
Need more manual and info for setup a new project. Thanks.

**Comment by ipselon** [comment]
@vanloswang 

> Beginning from version 2 Structor should be installed as a local npm module into react-boilerplate project.

> As far as Structor uses a custom metadata in order to operate the project's components, there is a fork of react-boilerplate project genuinely prepared for Structor.

> Please find the instruction of how to install and start working with Structor in compatible fork of the react-boilerplate project here: https://github.com/ipselon/react-boilerplate;

**Comment by vanloswang** [comment]
@ipselon I have react-boilerplate example app runs ok. but I did not get informatios about how to access structor ui, so how can I use it?

**Comment by Dmytro-Medzatiy** [comment]
@vanloswang 
- `npm run structor`
- go to `localhost:2222/structor`
- compose component
- use one of the available generators to create React Component
- `import` and use it in your project code

**Comment by vanloswang** [comment]
@ipselon @Dmytro-Medzatiy Run 'npm run structor' failed on both Windows 10 and CentOS 7, The error info on CentOS 7 is as follow:
```bash
npm run structor        
npm ERR! Linux 3.10.0-327.28.2.el7.x86_64
npm ERR! argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "run" "structor"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3

npm ERR! missing script: structor
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ws/webdev/react-boilerplate-3.1.0/npm-debug.log
```
Full informations in npm-debug.log is as following:
```bash
cat npm-debug.log 
0 info it worked if it ends with ok
1 verbose cli [ '/root/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v6.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'structor' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose stack Error: missing script: structor
4 verbose stack     at run (/root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/run-script.js:151:19)
4 verbose stack     at /root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/run-script.js:61:5
4 verbose stack     at /root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:356:5
4 verbose stack     at checkBinReferences_ (/root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:320:45)
4 verbose stack     at final (/root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:354:3)
4 verbose stack     at then (/root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:124:5)
4 verbose stack     at /root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:311:12
4 verbose stack     at /root/.nvm/versions/node/v6.5.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16
4 verbose stack     at tryToString (fs.js:455:3)
4 verbose stack     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
5 verbose cwd /home/ws/webdev/react-boilerplate-3.1.0
6 error Linux 3.10.0-327.28.2.el7.x86_64
7 error argv "/root/.nvm/versions/node/v6.5.0/bin/node" "/root/.nvm/versions/node/v6.5.0/bin/npm" "run" "structor"
8 error node v6.5.0
9 error npm  v3.10.3
10 error missing script: structor
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]
```

structor is installed by npm, Why there is no script: structor?

**Comment by ipselon** [comment]
@vanlosvang are you sure you have cloned a fork of the React Boilerplate? https://github.com/ipselon/react-boilerplate

**Comment by vanloswang** [comment]
@ipselon setup react-boilerplate by https://github.com/ipselon/react-boilerplate/archive/v3.1.0.zip

**Comment by ipselon** [comment]
@vanloswang 
Actually, there are only releases of main repo (not forks) in the releases list because I did'n make any releases of my fork so far. Consequently, you have to download an archive file with master branch of the fork: https://github.com/ipselon/react-boilerplate/archive/master.zip

**Comment by vanloswang** [comment]
@ipselon Thanks,The master branch runs ok.

**Comment by abhishek462** [comment]
@ipselon i have cloned master branch but still given error structor script missing
