### ISSUE TITLE
Important component index file with wrong path 

### ISSUE THREAD

**Issue by AndrewMcSwain** [ipselon/structor#75]
The opening page refers to an index file :

" Each of the project's boilerplates has its own set of components listed in the index file in meta folder of the project .structor/src/index.js. To have an ability to use some third-party component, which was not generated in Structor, you have to include a component's reference into this index file"

However my .structor/src/ directory does not contain said file.

**Comment by ipselon** [comment]
@AndrewMcSwain All above is true only for Structor version 1.x
