### ISSUE TITLE
 Cannot find module setup.js

### ISSUE THREAD

**Issue by tyv** [ipselon/structor#77]
```bash
$ npm run setup
...
module.js:327
    throw err;
    ^

Error: Cannot find module '/Users/yuriyt/projects/react-boilerplate/internals/scripts/setup.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3

```

**Comment by ipselon** [comment]
@tyv, I believe you just missed lines in Readme :-)

"Please find the instruction of how to install and start working with Structor in compatible fork of the react-boilerplate project here: https://github.com/ipselon/react-boilerplate"

As far as Structor is tightly integrated with `react-boilerplate`, to install and run Structor in the environment of `react-boilerplate` you should first clone or download the fork (find it by the link above) and then run `npm run setup` command in directory which contains the source code of `react-boilerplate` fork.

After you successfully set up the environment you can just run Structor by command: `npm run structor`.

**Comment by tyv** [comment]
it is continuously fails in any attempts and configurations: npm 2x and 3x, `npm i && npm setup` or just `npm setup` after clone

https://yadi.sk/i/dli4k1OKxxEGB

**Comment by ipselon** [comment]
@tyv could you try to clone and set up `react-boileplate` repo itself (not this fork)? Once it failed, I'll try to create an issue for that project. Otherwise I'll tackle with my fork...

**Comment by tyv** [comment]
original sets up environment just well. 
I can take a look tomorrow for reasons.

**Comment by tyv** [comment]
it looks like network issues on npm yesterday. 
yesterday I've tried on 3 different networks and many setups. 
today it installs well.
