### ISSUE TITLE
Cannot GET /structor-deskpage/home

### ISSUE THREAD

**Issue by ScorpiusJin** [ipselon/structor#79]
hi, i follow readme.md to run a demo. but failed.
`1. sudo npm install strcutor -g`
`2. git clone https://github.com/ipselon/react-boilerplate.git`
`3. npm run setup`
`4. npm run structor`

Open in the browser: http://localhost:2222/structor

![image](https://cloud.githubusercontent.com/assets/1516678/20225844/6f5c265c-a880-11e6-9fc4-2647d95c40c2.png)

**Comment by ipselon** [comment]
@ScorpiusJin, there is no **1.**  item in the instruction. Try all steps again but without the first item.

https://github.com/ipselon/react-boilerplate#quick-start-changed
