### ISSUE TITLE
Webpack issue involving fetch(), whatwg-fetch(), and polyfill loading

### ISSUE THREAD

**Issue by theanthonyplan** [ipselon/structor#82]
Have been having a strange problem over the last few days while trying to import and use any of the promise-based fetch() modules.  Here's the solution I found-- update the .structor/webpack.base.js file to reflect:

`
new webpack.NoEmitOnErrorsPlugin(),
new webpack.ProvidePlugin({
       // make fetch available
      fetch: 'exports-loader?self.fetch!whatwg-fetch',
}),
`

there are 2 changes, the first is that the -loader suffix was missing from exports, and second is the NoEmitOnErrorsPlugin needed updating after webpack was complaining about using a deprecated module.

Not sure if this is known or not, but I wanted to document it for anyone else that might be experiencing these issues.

Thanks again for your hard work!

**Comment by squirmsound** [comment]
My solution was to create a class.

```
import 'whatwg-fetch';

class ClientFetch {
  constructor(props) {
    this.fetch = this.fetch.bind(this);
    this.Headers = this.fetch.Headers;
    this.Request = this.fetch.Request;
    this.Response = this.fetch.Response;
  }
}

export default ClientFetch;
```
