### ISSUE TITLE
Installation Issue -- SyntaxError: block-scoped declarations

### ISSUE THREAD

**Issue by theanthonyplan** [ipselon/structor#86]
Hey Alex was hoping to check out the new build but unfortunately I ran into some trouble while installing structor.  Here is the error output:

structor@2.2.0 postinstall /home/ubuntu/workspace/structor-starter/node_modules/structor
> node ./postexec.js

/home/ubuntu/workspace/structor-starter/node_modules/structor/postexec.js:57
                        let packageFileName = packageVersion + META_REPO_ARCHIVE_EXT;
                        ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

Thanks again for your help!

**Comment by ipselon** [comment]
@theanthonyplan,

what version of node you are using?

**Comment by theanthonyplan** [comment]
This machine is running 4.8.1 

This isn't the normal machine I use for structor so that hadn't even crossed my mind.  Which version of node should I be using?

**Comment by ipselon** [comment]
@theanthonyplan, use at least >=6

**Comment by theanthonyplan** [comment]
awesome, it works perfectly now, thanks for the help!
