### ISSUE TITLE
not an issue (bootstrap question)

### ISSUE THREAD

**Issue by benjaminderei** [ipselon/structor#89]
Hello !

i'm a beginner with node / npm / webpack / react / ... and structor seems ideal to understand a little more react. But i'm wasting a lot of time searching how to do things.

can you write a little tutorial on how to add bootstrap to structor app ? (maybe just a little advice :)
i think it may help a lot of lost beginners !

Thx for structor
++

**Comment by ipselon** [comment]
Hi @benjaminderei! Sorry for the late response. 

I just pushed a new chapter about [Structor Market](https://github.com/ipselon/structor/blob/master/docs/structor-market.md#structor-market) where you can read about how to install new components. 

There is only one package of components on the market so far - Material UI set. But you can take a look at how it is injected into Structor's Library. 

Hope this help. If you still have questions, let me know.

**Comment by ipselon** [comment]
I'm closing it because of a new chapter.
