### ISSUE TITLE
Material-UI boilerplates needs peer dependencies under NPM 3

### ISSUE THREAD

**Issue by neverfox** [ipselon/structor#9]
The boilerplate will fail to install correctly with NPM 3, which no longer automatically installs peer dependencies, namely the `react-addons-` dependencies required by material-ui.

**Comment by ipselon** [comment]
@neverfox Thanks. From now all boilerplates which are presented on Structor Market are located on GitHub. So, you may add PR to this repo: https://github.com/ipselon/material-ui-prepack
