### ISSUE TITLE
Obtaining project status error. Not Found

### ISSUE THREAD

**Issue by sheweichun** [ipselon/structor#90]
1.I install structor by `npm install -g structor`
2.I run structor
3.when i open `http://192.168.125.119:2222/structor/` in browser,I get `Obtaining project status error. Not Found` error

How could I solve this

**Comment by ipselon** [comment]
Please follow "Getting Started" chapter https://github.com/ipselon/structor/blob/master/docs/README.md#getting-started

**Comment by sheweichun** [comment]
`"scripts": {
    "prebuild": "npm run build:clean",
    "build": "cross-env NODE_ENV=production webpack --config internals/webpack/webpack.prod.babel.js --color -p --progress",
    "build:clean": "rimraf ./build",
    "start": "cross-env NODE_ENV=development node server",
    "start:production": "npm run build && npm run start:prod",
    "start:prod": "cross-env NODE_ENV=production node server",
    "lint": "npm run lint:js",
    "lint:eslint": "eslint --ignore-path .stylelintignore",
    "lint:js": "npm run lint:eslint -- . ",
    "lint:staged": "lint-staged"
  }`
in the structor-starter's package.json,I can't find script `structor`,so when I run `npm run structor`,I got `missing script: structor`

**Comment by ipselon** [comment]
* Clone or download the repo structor-starter from GitHub

**Comment by sheweichun** [comment]
I do it as you say,can you try it by yourself? I can't find render script in package.json

**Comment by ipselon** [comment]
@sheweichun,

> I can't find render script in package.json

What script do you mean?

Could you describe steps you made in order to reproduce the error?

**Comment by sheweichun** [comment]
Clone or download the repo structor-starter from GitHub
npm install
npm install structor
npm run structor

I got ` missing script: structor`

**Comment by sheweichun** [comment]
I am ok,thank you very much
