### ISSUE TITLE
cannot GET /structor-deskpage/home

### ISSUE THREAD

**Issue by sjashwin** [ipselon/structor#95]
![screenshot 49](https://cloud.githubusercontent.com/assets/7351156/25792460/542ff5bc-33e4-11e7-9a44-c6d1d812b206.png)
Why is this error produced? Using nodejs v6.0

**Comment by ipselon** [comment]
@sjashwin,

Try to run Structor in verbose mode. Find and change the line in `package.json` file in `scripts` section:

`"structor": "structor"` to `"structor": "structor -v"`

Run Structor again and look at the console output.

Also, try to read the console output in the browser.

**Comment by sjashwin** [comment]
@ipselon this is the error in the console
Error happened during server initialization:
Webpack config was not found. TypeError: webpack.NoEmitOnErrorsPlugin is not a constructor

console output in browser:
server responded with error 404.

I suppose the file "/structor-deskpage/home" is missing.

**Comment by ipselon** [comment]
@sjashwin,

Could you write down steps in order to reproduce issue?

**Comment by sjashwin** [comment]
@ipselon 
I reinstalled the whole package from scratch.
This time when the server runs I get this in the console.

![screenshot 51](https://cloud.githubusercontent.com/assets/7351156/25839279/a6613c6c-34b4-11e7-9ebf-77c38d132fcb.png)

Steps:
1. cloned the repo
2. npm install
3. npm install structor
4. npm run structor

Browser console says localhost:3000 404 not found.

Did i miss something?

**Comment by ipselon** [comment]
Could you show your `package.json` file?

**Comment by sjashwin** [comment]
@ipselon 
Thanks, I resolved it. Had to move into the app directory and run the command >> npm run structor.
