### ISSUE TITLE
can't start structor error during server initialization

### ISSUE THREAD

**Issue by eborst** [ipselon/structor#96]
PS D:\Projects\frontend\structor-starter> npm run structor

> starter-app@0.0.1 structor D:\Projects\frontend\structor-starter
> structor

Error happened during server initialization:
Unknown plugin "transform-react-remove-prop-types" specified in "D:\\Projects\\frontend\\structor-starter\\package.json.env.production" at 0, a
ttempted to resolve relative to "D:\\Projects\\frontend\\structor-starter"

**Comment by eborst** [comment]
I just followed the documentation cloned the repo and installed the modules.

**Comment by eborst** [comment]
hmm look like you are missing some dependencies.
I have installed:
npm install --save-dev babel-plugin-transform-react-remove-prop-types
npm install --save-dev babel-plugin-transform-react-constant-elements
npm install --save-dev babel-plugin-transform-react-inline-elements

Now Structor is starting....

**Comment by ipselon** [comment]
@eborst,

Could you explain where is specified in starter project this plugin `transform-react-remove-prop-types` ?

And what is the purpose of file `package.json.env.production`? There is no such file in `stuctor-starter` repo.

**Comment by eborst** [comment]
Oh well I cloned the repo.
in your package.json there is this from line 37:
"env": {"production": {"only": ["app" ],"plugins": 
["transform-react-remove-prop-types","transform-react-constant-elements","transform-react-inline-elements" 
] } }

------ Origineel bericht ------
Van: "Alex Pustovalov" <notifications@github.com>
Aan: "ipselon/structor" <structor@noreply.github.com>
Cc: "eborst" <edward.borst@ebotech.nl>; "Mention" 
<mention@noreply.github.com>
Verzonden: 15-5-2017 10:40:02
Onderwerp: Re: [ipselon/structor] can't start structor error during 
server initialization (#96)

**Comment by ipselon** [comment]
@eborst,

These plugins are provided no in `package.json` file. But in Webpack config for production. And it does not have any impact on Structor running process...

**Comment by eborst** [comment]
As said I just followed the documentation. 
I just did exactly what was told... could this be related to the other issue?

**Comment by ipselon** [comment]
I see. As I said in your another issue, please provide files I mentioned in order to understand what is happening and why.

**Comment by ipselon** [comment]
I'm closing this issue, it seems that this is the same issue as https://github.com/ipselon/structor/issues/97
