### ISSUE TITLE
no build Directory

### ISSUE THREAD

**Issue by xstable** [ipselon/structor#98]
In the tutorial - at the very end of it - you wrote: 
Additionally, please find the compiled bundle of the application in <PROJECT_DIR>/build directory.

I've done all the Steps, but there is no build-Directory at all. 
I even don't see any error-message - but the green Popup for successfull app export.

**Comment by xstable** [comment]
Ah, I see... you have only to put some additional Information to this sentence:

> Additionally, please find the compiled bundle of the application in <PROJECT_DIR>/build directory

You have to add the Information, that this _build_ Directory will be created after running: 
`npm run start:production`

**Comment by ipselon** [comment]
@xstable,

Thanks for suggestion! Will do.
